# Generated by Django 5.1 on 2024-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_location_lat_remove_location_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='building_image',
            field=models.ImageField(null=True, upload_to='building_images/'),
        ),
    ]
